endpoints:
  base-login: /login
  login:
    iniciar: /iniciar
    registrar: /registrar
jwt:
  expiration-time-ms: 86400000
  secret-key: NXRR+SVc/iI0UXHhZHOBMv92pTgFVHqPZoNlNV6onIo=
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: reservation
  application:
    name: login

server:
  servlet:
    context-path: /api/v1